version = 0.1

[default.deploy.parameters]
stack_name = "mlops-swo-env"
s3_bucket = "swo-ngoctran-public"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false
disable_rollback = false
