AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MLOps - Trigger KMeans Preprocessing + Training

Parameters:
  ProcessingImageUri:
    Type: String
    Default: 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3

  S3Bucket:
    Type: String
    Default: swo-ngoctran-public

Resources:

  TriggerPreprocessingKMeans:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trigger-preprocess-kmeans
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/trigger_preprocessing/
      Timeout: 120
      MemorySize: 512
      Role: arn:aws:iam::975049948583:role/LambdaSageMakerInferencePolicy
      Environment:
        Variables:
          SAGEMAKER_ROLE_ARN: arn:aws:iam::975049948583:role/LambdaSageMakerInferencePolicy
          PROCESSING_IMAGE_URI: !Ref ProcessingImageUri
          CODE_PREFIX: mlops/jobs/01_preprocessing_kmeans/
          S3_BUCKET: !Ref S3Bucket
          DATA_PREFIX: mlops/raw_data/
          OUTPUT_PREFIX: mlops/pipelines/01_preprocessing_kmeans/

      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /trigger-preprocess
            Method: post

  TriggerTrainingKMeans:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trigger-training-kmeans
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/trigger_training/
      Timeout: 120
      MemorySize: 512
      Role: arn:aws:iam::975049948583:role/LambdaSageMakerInferencePolicy
      Environment:
        Variables:
          SAGEMAKER_ROLE_ARN: arn:aws:iam::975049948583:role/LambdaSageMakerInferencePolicy
          PROCESSING_IMAGE_URI: !Ref ProcessingImageUri
          CODE_PREFIX: mlops/jobs/02_training_kmeans/
          S3_BUCKET: !Ref S3Bucket
          OUTPUT_PREFIX: mlops/pipelines/02_training_kmeans/

      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /trigger-training
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint"
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
