name: Sync Python files to S3 on push

on:
  push:
    paths:
      - '**.py'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          set -a
          source config/global.env
          set +a

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload modified .py files to S3
        run: |
          CHANGED=$(git ls-files -m | grep '\.py$' || true)
          for FILE in $CHANGED; do
            echo "🔁 Uploading $FILE to s3://$S3_BUCKET/$CODE_PREFIX$FILE"
            aws s3 cp "$FILE" "s3://$S3_BUCKET/$CODE_PREFIX$FILE"
          done
