name: Sync pipelines to S3 on push

on:
  push:
    paths:
      - 'pipelines/**'

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load env vars
        run: |
          cat config/global.env >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Discover and sync all pipelines automatically
        run: |
          for dir in pipelines/*; do
            pipeline_name=$(basename "$dir")
            s3_path="mlops/jobs/${pipeline_name}/pipelines/${pipeline_name}/"
            echo "🔁 Syncing $dir to s3://$S3_BUCKET/$s3_path"
            aws s3 sync "$dir" "s3://$S3_BUCKET/$s3_path"
          done
